version: '1'
services:
  ui:
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - "4200:4200"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: VeryComplex123Password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
      
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
    - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=W1EHUB_V2;User=sa;Password=VeryComplex123Password"
  