// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W1EHUB.Repo.Data;

#nullable disable

namespace W1EHUB.Repo.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("W1EHUB.Core.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Main St, Sampleville",
                            Country = "Country 1",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company1.com",
                            Name = "Company 1",
                            Region = "Region 1",
                            Telephone = "123-456-1000",
                            TypeOfCompany = "Type Of Company1",
                            Website = "www.company1.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 Main St, Sampleville",
                            Country = "Country 2",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company2.com",
                            Name = "Company 2",
                            Region = "Region 2",
                            Telephone = "123-456-2000",
                            TypeOfCompany = "Type Of Company2",
                            Website = "www.company2.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Main St, Sampleville",
                            Country = "Country 3",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company3.com",
                            Name = "Company 3",
                            Region = "Region 3",
                            Telephone = "123-456-3000",
                            TypeOfCompany = "Type Of Company3",
                            Website = "www.company3.com"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 Main St, Sampleville",
                            Country = "Country 4",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company4.com",
                            Name = "Company 4",
                            Region = "Region 4",
                            Telephone = "123-456-4000",
                            TypeOfCompany = "Type Of Company4",
                            Website = "www.company4.com"
                        },
                        new
                        {
                            Id = 5,
                            Address = "5 Main St, Sampleville",
                            Country = "Country 5",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company5.com",
                            Name = "Company 5",
                            Region = "Region 5",
                            Telephone = "123-456-5000",
                            TypeOfCompany = "Type Of Company5",
                            Website = "www.company5.com"
                        },
                        new
                        {
                            Id = 6,
                            Address = "6 Main St, Sampleville",
                            Country = "Country 6",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company6.com",
                            Name = "Company 6",
                            Region = "Region 6",
                            Telephone = "123-456-6000",
                            TypeOfCompany = "Type Of Company6",
                            Website = "www.company6.com"
                        },
                        new
                        {
                            Id = 7,
                            Address = "7 Main St, Sampleville",
                            Country = "Country 7",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company7.com",
                            Name = "Company 7",
                            Region = "Region 7",
                            Telephone = "123-456-7000",
                            TypeOfCompany = "Type Of Company7",
                            Website = "www.company7.com"
                        },
                        new
                        {
                            Id = 8,
                            Address = "8 Main St, Sampleville",
                            Country = "Country 8",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company8.com",
                            Name = "Company 8",
                            Region = "Region 8",
                            Telephone = "123-456-8000",
                            TypeOfCompany = "Type Of Company8",
                            Website = "www.company8.com"
                        },
                        new
                        {
                            Id = 9,
                            Address = "9 Main St, Sampleville",
                            Country = "Country 9",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company9.com",
                            Name = "Company 9",
                            Region = "Region 9",
                            Telephone = "123-456-9000",
                            TypeOfCompany = "Type Of Company9",
                            Website = "www.company9.com"
                        },
                        new
                        {
                            Id = 10,
                            Address = "10 Main St, Sampleville",
                            Country = "Country 10",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company10.com",
                            Name = "Company 10",
                            Region = "Region 10",
                            Telephone = "123-456-10000",
                            TypeOfCompany = "Type Of Company10",
                            Website = "www.company10.com"
                        },
                        new
                        {
                            Id = 11,
                            Address = "11 Main St, Sampleville",
                            Country = "Country 11",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company11.com",
                            Name = "Company 11",
                            Region = "Region 11",
                            Telephone = "123-456-11000",
                            TypeOfCompany = "Type Of Company11",
                            Website = "www.company11.com"
                        },
                        new
                        {
                            Id = 12,
                            Address = "12 Main St, Sampleville",
                            Country = "Country 12",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company12.com",
                            Name = "Company 12",
                            Region = "Region 12",
                            Telephone = "123-456-12000",
                            TypeOfCompany = "Type Of Company12",
                            Website = "www.company12.com"
                        },
                        new
                        {
                            Id = 13,
                            Address = "13 Main St, Sampleville",
                            Country = "Country 13",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company13.com",
                            Name = "Company 13",
                            Region = "Region 13",
                            Telephone = "123-456-13000",
                            TypeOfCompany = "Type Of Company13",
                            Website = "www.company13.com"
                        },
                        new
                        {
                            Id = 14,
                            Address = "14 Main St, Sampleville",
                            Country = "Country 14",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company14.com",
                            Name = "Company 14",
                            Region = "Region 14",
                            Telephone = "123-456-14000",
                            TypeOfCompany = "Type Of Company14",
                            Website = "www.company14.com"
                        },
                        new
                        {
                            Id = 15,
                            Address = "15 Main St, Sampleville",
                            Country = "Country 15",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company15.com",
                            Name = "Company 15",
                            Region = "Region 15",
                            Telephone = "123-456-15000",
                            TypeOfCompany = "Type Of Company15",
                            Website = "www.company15.com"
                        },
                        new
                        {
                            Id = 16,
                            Address = "16 Main St, Sampleville",
                            Country = "Country 16",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company16.com",
                            Name = "Company 16",
                            Region = "Region 16",
                            Telephone = "123-456-16000",
                            TypeOfCompany = "Type Of Company16",
                            Website = "www.company16.com"
                        },
                        new
                        {
                            Id = 17,
                            Address = "17 Main St, Sampleville",
                            Country = "Country 17",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company17.com",
                            Name = "Company 17",
                            Region = "Region 17",
                            Telephone = "123-456-17000",
                            TypeOfCompany = "Type Of Company17",
                            Website = "www.company17.com"
                        },
                        new
                        {
                            Id = 18,
                            Address = "18 Main St, Sampleville",
                            Country = "Country 18",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company18.com",
                            Name = "Company 18",
                            Region = "Region 18",
                            Telephone = "123-456-18000",
                            TypeOfCompany = "Type Of Company18",
                            Website = "www.company18.com"
                        },
                        new
                        {
                            Id = 19,
                            Address = "19 Main St, Sampleville",
                            Country = "Country 19",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company19.com",
                            Name = "Company 19",
                            Region = "Region 19",
                            Telephone = "123-456-19000",
                            TypeOfCompany = "Type Of Company19",
                            Website = "www.company19.com"
                        },
                        new
                        {
                            Id = 20,
                            Address = "20 Main St, Sampleville",
                            Country = "Country 20",
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@company20.com",
                            Name = "Company 20",
                            Region = "Region 20",
                            Telephone = "123-456-20000",
                            TypeOfCompany = "Type Of Company20",
                            Website = "www.company20.com"
                        });
                });

            modelBuilder.Entity("W1EHUB.Core.Model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 1",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 1",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 1",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 2",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 2",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 2",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 3",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 3",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 3",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 4",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 4",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 4",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 5",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 5",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 5",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 6",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 6",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 6",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 7",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 7",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 7",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 8",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 8",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 8",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 25,
                            CompanyId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 9",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 26,
                            CompanyId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 9",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 27,
                            CompanyId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 9",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 28,
                            CompanyId = 10,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 10",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 29,
                            CompanyId = 10,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 10",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 30,
                            CompanyId = 10,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 10",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 31,
                            CompanyId = 11,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 11",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 32,
                            CompanyId = 11,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 11",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 33,
                            CompanyId = 11,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 11",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 34,
                            CompanyId = 12,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 12",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 35,
                            CompanyId = 12,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 12",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 36,
                            CompanyId = 12,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 12",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 37,
                            CompanyId = 13,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 13",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 38,
                            CompanyId = 13,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 13",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 39,
                            CompanyId = 13,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 13",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 40,
                            CompanyId = 14,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 14",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 41,
                            CompanyId = 14,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 14",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 42,
                            CompanyId = 14,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 14",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 43,
                            CompanyId = 15,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 15",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 44,
                            CompanyId = 15,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 15",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 45,
                            CompanyId = 15,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 15",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 46,
                            CompanyId = 16,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 16",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 47,
                            CompanyId = 16,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 16",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 48,
                            CompanyId = 16,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 16",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 49,
                            CompanyId = 17,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 17",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 50,
                            CompanyId = 17,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 17",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 51,
                            CompanyId = 17,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 17",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 52,
                            CompanyId = 18,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 18",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 53,
                            CompanyId = 18,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 18",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 54,
                            CompanyId = 18,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 18",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 55,
                            CompanyId = 19,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 19",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 56,
                            CompanyId = 19,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 19",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 57,
                            CompanyId = 19,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 19",
                            Type = "Project 3 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 58,
                            CompanyId = 20,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 1",
                            Nature = "Project 1 Nature",
                            Title = "Project 1 for Company 20",
                            Type = "Project 1 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 59,
                            CompanyId = 20,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 2",
                            Nature = "Project 2 Nature",
                            Title = "Project 2 for Company 20",
                            Type = "Project 2 Type",
                            Year = 2023
                        },
                        new
                        {
                            Id = 60,
                            CompanyId = 20,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = "Level 3",
                            Nature = "Project 3 Nature",
                            Title = "Project 3 for Company 20",
                            Type = "Project 3 Type",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("W1EHUB.Core.Model.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("StaffMember");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 10,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 10,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 11,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 11,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 12,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 12,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 25,
                            CompanyId = 13,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 26,
                            CompanyId = 13,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 27,
                            CompanyId = 14,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 28,
                            CompanyId = 14,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 29,
                            CompanyId = 15,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 30,
                            CompanyId = 15,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 31,
                            CompanyId = 16,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 32,
                            CompanyId = 16,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 33,
                            CompanyId = 17,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 34,
                            CompanyId = 17,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 35,
                            CompanyId = 18,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 36,
                            CompanyId = 18,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 37,
                            CompanyId = 19,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 38,
                            CompanyId = 19,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        },
                        new
                        {
                            Id = 39,
                            CompanyId = 20,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 1",
                            Role = "Role 1"
                        },
                        new
                        {
                            Id = 40,
                            CompanyId = 20,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Staff Member 2",
                            Role = "Role 2"
                        });
                });

            modelBuilder.Entity("W1EHUB.Core.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 10, 25, 18, 49, 36, 544, DateTimeKind.Local).AddTicks(9557),
                            Email = "a@abc.com",
                            Password = "aaa"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 10, 25, 18, 49, 36, 544, DateTimeKind.Local).AddTicks(9570),
                            Email = "b@abc.com",
                            Password = "bbb"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 10, 25, 18, 49, 36, 544, DateTimeKind.Local).AddTicks(9571),
                            Email = "c@abc.com",
                            Password = "ccc"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2023, 10, 25, 18, 49, 36, 544, DateTimeKind.Local).AddTicks(9573),
                            Email = "d@abc.com",
                            Password = "ddd"
                        });
                });

            modelBuilder.Entity("W1EHUB.Core.Model.Project", b =>
                {
                    b.HasOne("W1EHUB.Core.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("W1EHUB.Core.Model.StaffMember", b =>
                {
                    b.HasOne("W1EHUB.Core.Model.Company", "Company")
                        .WithMany("StaffMembers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("W1EHUB.Core.Model.Company", b =>
                {
                    b.Navigation("StaffMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
