version: '1'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: VeryComplex123Password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
